title: 'g-g-lim.github.io'
description: "hello world"
baseurl: "/"
url: "https://g-g-lim.github.io"

header_pages:
  - index.md
  - posts.md
  - about.md
  - contact.md

style: dark

footer: 'copyright &copy; 1994 g-g-lim'

# Build settings
markdown: kramdown
remote_theme: b2a3e8/jekyll-theme-console